types:
  - oak:
      block: OAK_PLANKS
      slab: OAK_SLAB
  - spruce:
      block: SPRUCE_PLANKS
      slab: SPRUCE_SLAB
  - birch:
      block: BIRCH_PLANKS
      slab: BIRCH_SLAB
  - jungle:
      block: JUNGLE_PLANKS
      slab: JUNGLE_SLAB
  - acacia:
      block: ACACIA_PLANKS
      slab: ACACIA_SLAB
  - dark_oak:
      block: DARK_OAK_PLANKS
      slab: DARK_OAK_SLAB
  - mangrove:
      block: MANGROVE_PLANKS
      slab: MANGROVE_SLAB
  - cherry:
      block: CHERRY_PLANKS
      slab: CHERRY_SLAB
  - bamboo:
      block: BAMBOO_MOSAIC
      slab: BAMBOO_MOSAIC_SLAB
  - crimson:
      block: CRIMSON_PLANKS
      slab: CRIMSON_SLAB
  - warped:
      block: WARPED_PLANKS
      slab: WARPED_SLAB
  - stone:
      block: STONE
      slab: STONE_SLAB
  - cobblestone:
      block: COBBLESTONE
      slab: COBBLESTONE_SLAB
  - mossy_cobblestone:
      block: MOSSY_COBBLESTONE
      slab: MOSSY_COBBLESTONE_SLAB
  - smooth_stone:
      block: SMOOTH_STONE
      slab: SMOOTH_STONE_SLAB
  - stone_bricks:
      block: STONE_BRICKS
      slab: STONE_BRICK_SLAB
  - mossy_stone_briks:
      block: MOSSY_STONE_BRICKS
      slab: MOSSY_STONE_BRICK_SLAB
  - granite:
      block: GRANITE
      slab: GRANITE_SLAB
  - polished_granite:
      block: POLISHED_GRANITE
      slab: POLISHED_GRANITE_SLAB
  - andesite:
      block: ANDESITE
      slab: ANDESITE_SLAB
  - polished_andesite:
      block: POLISHED_ANDESITE
      slab: POLISHED_ANDESITE_SLAB
  - diorite:
      block: DIORITE
      slab: DIORITE_SLAB
  - polished_diorite:
      block: POLISHED_DIORITE
      slab: POLISHED_DIORITE_SLAB
  - cobbled_deepslate:
      block: COBBLED_DEEPSLATE
      slab: COBBLED_DEEPSLATE_SLAB
  - polished_deepslate:
      block: POLISHED_DEEPSLATE
      slab: POLISHED_DEEPSLATE_SLAB
  - deepslate_bricks:
      block: DEEPSLATE_BRICKS
      slab: DEEPSLATE_BRICK_SLAB
  - deepslate_tiles:
      block: DEEPSLATE_TILES
      slab: DEEPSLATE_TILE_SLAB
  - bricks:
      block: BRICKS
      slab: BRICK_SLAB
  - mud_bricks:
      block: MUD_BRICKS
      slab: MUD_BRICK_SLAB
  - sandstone:
      block: SANDSTONE
      slab: SANDSTONE_SLAB
  - smooth_sandstone:
      block: SMOOTH_SANDSTONE
      slab: SMOOTH_SANDSTONE_SLAB
  - cut_sandstone:
      block: CUT_SANDSTONE
      slab: CUT_SANDSTONE_SLAB
  - red_sandstone:
      block: RED_SANDSTONE
      slab: RED_SANDSTONE_SLAB
  - smooth_red_sandstone:
      block: SMOOTH_RED_SANDSTONE
      slab: SMOOTH_RED_SANDSTONE_SLAB
  - cut_red_sandstone:
      block: CUT_RED_SANDSTONE
      slab: CUT_RED_SANDSTONE_SLAB
  - prismarine:
      block: PRISMARINE
      slab: PRISMARINE_SLAB
  - prismarine_bricks:
      block: PRISMARINE_BRICKS
      slab: PRISMARINE_BRICK_SLAB
  - dark_prismarine:
      block: DARK_PRISMARINE
      slab: DARK_PRISMARINE_SLAB
  - nether_brick:
      block: NETHER_BRICK
      slab: NETHER_BRICK_SLAB
  - red_nether_brick:
      block: RED_NETHER_BRICKS
      slab: RED_NETHER_BRICK_SLAB
  - blackstone:
      block: BLACKSTONE
      slab: BLACKSTONE_SLAB
  - polished_blackstone:
      block: POLISHED_BLACKSTONE
      slab: POLISHED_BLACKSTONE_SLAB
  - polished_blackstone_brick:
      block: POLISHED_BLACKSTONE_BRICKS
      slab: POLISHED_BLACKSTONE_BRICK_SLAB
  - end_stone_bricks:
      block: END_STONE_BRICKS
      slab: END_STONE_BRICK_SLAB
  - purpur:
      block: PURPUR_BLOCK
      slab: PURPUR_SLAB
  - quartz:
      block: QUARTZ_BLOCK
      slab: QUARTZ_SLAB
  - smooth_quartz:
      block: SMOOTH_QUARTZ
      slab: SMOOTH_QUARTZ_SLAB
  - cut_copper:
      block: CUT_COPPER
      slab: CUT_COPPER_SLAB
  - exposed_cut_copper:
      block: EXPOSED_CUT_COPPER
      slab: EXPOSED_CUT_COPPER_SLAB
  - oxidized_cut_copper:
      block: OXIDIZED_CUT_COPPER
      slab: OXIDIZED_CUT_COPPER_SLAB
  - waxed_cut_copper:
      block: WAXED_CUT_COPPER
      slab: WAXED_CUT_COPPER_SLAB
  - waxed_exposed_cut_copper:
      block: WAXED_EXPOSED_CUT_COPPER
      slab: WAXED_EXPOSED_CUT_COPPER_SLAB
  - waxed_oxidized_cut_copper:
      block: WAXED_OXIDIZED_CUT_COPPER
      slab: WAXED_OXIDIZED_CUT_COPPER_SLAB
  - waxed_weathered_cut_copper:
      block: WAXED_WEATHERED_CUT_COPPER
      slab: WAXED_WEATHERED_CUT_COPPER_SLAB
  - weathered_cut_copper:
      block: WEATHERED_CUT_COPPER
      slab: WEATHERED_CUT_COPPER_SLAB